Attempt to fix CI, log Rust publish inputs

diff --git a/.github/actions/publish/publish-rust/action.yml b/.github/actions/publish/publish-rust/action.yml
--- a/.github/actions/publish/publish-rust/action.yml
+++ b/.github/actions/publish/publish-rust/action.yml
@@ -8,8 +8,8 @@ inputs:
     description: 'the version to release under (e.g. `1.2.3-dev.1`)'
     required: true
   dry-run:
-    description: 'will not publish if set, but only log the potential result'
-    required: false
+    description: "'true' = only log potential result; 'false' = publish'"
+    required: true
 runs:
   using: "composite"
   steps:
@@ -29,4 +29,11 @@ runs:
     - name: Publish library to crates.io
       shell: sh
       # add to non-dry run `--no-confirm`
-      run: cargo release --workspace --token ${{ inputs.crates-token }} --isolated --no-dev-version --no-push --no-tag --verbose $(if [ ${{ inputs.dry-run }} == '' ]; then echo --execute; fi) ${{ inputs.version }}
+      run: |
+        echo "dry-run: '${{ inputs.dry-run }}'"
+        echo "version: '${{ inputs.version }}'"
+        if [[ ${{ inputs.dry-run }} != 'true' && ${{ inputs.dry-run }} != 'false' ]]; then 
+          echo "Invalid dry-run input"
+          exit 1
+        fi
+        cargo release --workspace --token ${{ inputs.crates-token }} --isolated --no-dev-version --no-push --no-tag --verbose $(if [ ${{ inputs.dry-run }} == 'false' ]; then echo --execute; fi) ${{ inputs.version }}
