log releases in case of failure

diff --git a/.github/actions/iota-rebase-sandbox/setup/action.yml b/.github/actions/iota-rebase-sandbox/setup/action.yml
--- a/.github/actions/iota-rebase-sandbox/setup/action.yml
+++ b/.github/actions/iota-rebase-sandbox/setup/action.yml
@@ -58,8 +58,17 @@ runs:
         
         echo "Looking for platform: $PLATFORM_TRIPLET"
 
-        # Note: Releases might be visible before all binaries are available
-        DOWNLOAD_URL=$(curl "https://api.github.com/repos/iotaledger/iota/releases" | jq -r 'map(select(.name | contains('\"$VERSION_SEARCH_STRING\"'))) | first | .assets | .[] | select(.browser_download_url | contains('\"$PLATFORM_TRIPLET\"')) | .browser_download_url')
+        curl "https://api.github.com/repos/iotaledger/iota/releases" > releases.json
+
+        {
+          # Note: Releases might be visible before all binaries are available
+          DOWNLOAD_URL=$(cat releases.json | jq -r 'map(select(.name | contains('\"$VERSION_SEARCH_STRING\"'))) | first | .assets | .[] | select(.browser_download_url | contains('\"$PLATFORM_TRIPLET\"')) | .browser_download_url')
+        } || {
+          # log releases in case of failure
+          cat releases.json
+          echo "could not parse release"
+          exit 1
+        }
 
         # Download and extract
         echo "Downloading from: $DOWNLOAD_URL"
