new upgrade script and updated setup to have toml cli

diff --git a/.github/actions/iota-rebase-sandbox/setup/action.yml b/.github/actions/iota-rebase-sandbox/setup/action.yml
--- a/.github/actions/iota-rebase-sandbox/setup/action.yml
+++ b/.github/actions/iota-rebase-sandbox/setup/action.yml
@@ -99,3 +99,20 @@ runs:
 
         # Start the network
         iota start --with-faucet ${{ inputs.logfile && format('> {0} 2>&1', inputs.logfile) || '' }} &
+    - name: Setup TOML CLI utils
+      shell: bash
+      run: |
+        set -e
+        mkdir -p toml-cli
+        cd toml-cli
+
+        DOWNNLOAD_URL = https://github.com/gnprice/toml-cli/releases/download/v0.2.3/toml-0.2.3-x86_64-linux.tar.gz
+        echo "Downloading from: $DOWNLOAD_URL"
+        curl -L -o toml-cli.tar.gz $DOWNLOAD_URL
+        tar -xzf toml-cli.tar.gz
+
+        echo "$PWD" >> $GITHUB_PATH
+        export PATH="$PWD:$PATH"
+
+        which toml || echo "toml not found in PATH"
+        ls -la "$PWD"
