move actions

diff --git a/.github/workflows/build-and-test.yml b/.github/workflows/build-and-test.yml
--- a/.github/workflows/build-and-test.yml
+++ b/.github/workflows/build-and-test.yml
@@ -41,85 +41,33 @@ jobs:
     steps:
       - uses: actions/checkout@v2
 
-      - name: Install stable toolchain
-        uses: actions-rs/toolchain@v1
-        with:
-          toolchain: stable
-          override: true
-
-      - name: Get current date
-        if: matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest'
-        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
-
-      - name: Get current date
-        if: matrix.os == 'windows-latest'
-        run: echo "CURRENT_DATE=$(Get-Date -Format "yyyy-MM-dd")" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
-
-      - name: Cache cargo
-        uses: actions/cache@v2.1.4
-        with:
-          # https://doc.rust-lang.org/cargo/guide/cargo-home.html#caching-the-cargo-home-in-ci
-          path: |
-            ~/.cargo/bin/
-            ~/.cargo/registry/index/
-            ~/.cargo/registry/cache/
-            ~/.cargo/git/db/
-          # Add date to the cache to keep it up to date
-          key: ${{ matrix.os }}-cargo-${{ github.job }}-${{ hashFiles('**/Cargo.toml') }}-${{ env.CURRENT_DATE }}
-          # Restore from outdated cache for speed
-          restore-keys: |
-            ${{ matrix.os }}-cargo-${{ github.job }}-${{ hashFiles('**/Cargo.toml') }}-
-            ${{ matrix.os }}-cargo-${{ github.job }}-
-            ${{ matrix.os }}-cargo-
-
-      # Generate Cargo.lock files for build, sccache cache keys.
-      # Allows dependencies updated on crates.io between runs to trigger storing an updated cache,
-      # which hashing Cargo.toml files alone does not.
-      - name: Cargo update
-        uses: actions-rs/cargo@v1
-        with:
-          command: update
-
-      - name: Cache build target
-        uses: actions/cache@v2.1.4
-        with:
-          path: target
-          # Add date to the cache to keep it up to date
-          key: ${{ matrix.os }}-target-${{ github.job }}-${{ hashFiles('**/Cargo.lock') }}
-          # Restore from outdated cache for speed
-          restore-keys: |
-            ${{ matrix.os }}-target-${{ github.job }}-
-            ${{ matrix.os }}-target-
-
-      - uses: './.github/actions/sccache/install-and-start-sccache-ubuntu'
-        name: install-and-start-sccache-ubuntu
-        if: matrix.os == 'ubuntu-latest'
-        with:
-          cache-path: ${{ matrix.sccache-path }}
-          cache-key: ${{ runner.os }}-sccache-${{ github.job }}-${{ hashFiles('**/Cargo.lock') }}
-          cache-restore-keys: |
-            ${{ runner.os }}-sccache-${{ github.job }}-
-            ${{ runner.os }}-sccache-
-
-      - uses: './.github/actions/sccache/install-and-start-sccache-windows'
+      - uses: './.github/actions/utils/get-current-time-windows'
         name: install-and-start-sccache-windows
         if: matrix.os == 'windows-latest'
-        with:
-          cache-path: ${{ matrix.sccache-path }}
-          cache-key: ${{ runner.os }}-sccache-${{ github.job }}-${{ hashFiles('**/Cargo.lock') }}
-          cache-restore-keys: |
-            ${{ runner.os }}-sccache-${{ github.job }}-
-            ${{ runner.os }}-sccache-
 
-      - uses: './.github/actions/sccache/install-and-start-sccache-macos'
+      - uses: './.github/actions/utils/get-current-time-ubuntu-macos'
+        name: install-and-start-sccache-macos
+        if: matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest'
+
+      - uses: './.github/actions/rust/setup'
+        name: rust-setup
+        with:
+          os: ${{ runner.os }}
+          job: ${{ github.job }}
+          sccache-path: ${{ matrix.sccache-path }}
+          current-time: ${{ env.CURRENT_DATE }}
+
+      - uses: './.github/actions/rust/sccache/install-and-start-sccache-ubuntu'
+        name: install-and-start-sccache-ubuntu
+        if: matrix.os == 'ubuntu-latest'
+        
+      - uses: './.github/actions/rust/sccache/install-and-start-sccache-windows'
+        name: install-and-start-sccache-windows
+        if: matrix.os == 'windows-latest'
+
+      - uses: './.github/actions/rust/sccache/install-and-start-sccache-macos'
         name: install-and-start-sccache-macos
         if: matrix.os == 'macos-latest'
-        with:
-          cache-path: ${{ matrix.sccache-path }}
-          cache-key: ${{ runner.os }}-sccache-${{ github.job }}-${{ hashFiles('**/Cargo.lock') }}
-          cache-restore-keys: |
-            ${{ runner.os }}-sccache-${{ github.job }}-
-            ${{ runner.os }}-sccache-
      
       - name: Build
         uses: actions-rs/cargo@v1
@@ -134,8 +82,13 @@ jobs:
           command: test
           args: --all --release
 
-      - name: Stop sccache server
-        run: sccache --stop-server || true
+      - uses: './.github/actions/rust/sccache/stop-sccache-windows'
+        name: install-and-start-sccache-windows
+        if: matrix.os == 'windows-latest'
+
+      - uses: './.github/actions/rust/sccache/stop-sccache-ubuntu-macos'
+        name: install-and-start-sccache-macos
+        if: matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest'
 
   build-and-test-libjose:
     runs-on: ubuntu-latest
@@ -167,110 +120,104 @@ jobs:
           command: test
           args: --manifest-path ./libjose/Cargo.toml --release
 
-  build-and-test-wasm:
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        os: [ ubuntu-latest ]
-        include:
-          - os: ubuntu-latest
-            sccache-path: /home/runner/.cache/sccache
-    env:
-      SCCACHE_DIR: ${{ matrix.sccache-path }}
-      CARGO_INCREMENTAL: 0 # disabled to reduce target cache size
-      RUSTC_WRAPPER: sccache
+  # build-and-test-wasm:
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       os: [ ubuntu-latest ]
+  #       include:
+  #         - os: ubuntu-latest
+  #           sccache-path: /home/runner/.cache/sccache
+  #   env:
+  #     SCCACHE_DIR: ${{ matrix.sccache-path }}
+  #     CARGO_INCREMENTAL: 0 # disabled to reduce target cache size
+  #     RUSTC_WRAPPER: sccache
 
-    steps:
-      - uses: actions/checkout@v2
+  #   steps:
+  #     - uses: actions/checkout@v2
 
-      - name: Install stable toolchain
-        uses: actions-rs/toolchain@v1
-        with:
-          toolchain: stable
-          override: true
+  #     - name: Install stable toolchain
+  #       uses: actions-rs/toolchain@v1
+  #       with:
+  #         toolchain: stable
+  #         override: true
 
-      - name: Install WASM toolchain
-        uses: actions-rs/toolchain@v1
-        with:
-          toolchain: stable
-          target: wasm32-unknown-unknown
+  #     - name: Install WASM toolchain
+  #       uses: actions-rs/toolchain@v1
+  #       with:
+  #         toolchain: stable
+  #         target: wasm32-unknown-unknown
 
-      - name: Cache cargo
-        uses: actions/cache@v2.1.4
-        with:
-          # https://doc.rust-lang.org/cargo/guide/cargo-home.html#caching-the-cargo-home-in-ci
-          path: |
-            ~/.cargo/bin/
-            ~/.cargo/registry/index/
-            ~/.cargo/registry/cache/
-            ~/.cargo/git/db/
-          # Add date to the cache to keep it up to date
-          key: ${{ matrix.os }}-cargo-${{ github.job }}-${{ hashFiles('**/Cargo.toml') }}-${{ env.CURRENT_DATE }}
-          # Restore from outdated cache for speed
-          restore-keys: |
-            ${{ matrix.os }}-cargo-${{ github.job }}-${{ hashFiles('**/Cargo.toml') }}-
-            ${{ matrix.os }}-cargo-${{ github.job }}-
-            ${{ matrix.os }}-cargo-
+  #     - name: Cache cargo
+  #       uses: actions/cache@v2.1.4
+  #       with:
+  #         # https://doc.rust-lang.org/cargo/guide/cargo-home.html#caching-the-cargo-home-in-ci
+  #         path: |
+  #           ~/.cargo/bin/
+  #           ~/.cargo/registry/index/
+  #           ~/.cargo/registry/cache/
+  #           ~/.cargo/git/db/
+  #         # Add date to the cache to keep it up to date
+  #         key: ${{ matrix.os }}-cargo-${{ github.job }}-${{ hashFiles('**/Cargo.toml') }}-${{ env.CURRENT_DATE }}
+  #         # Restore from outdated cache for speed
+  #         restore-keys: |
+  #           ${{ matrix.os }}-cargo-${{ github.job }}-${{ hashFiles('**/Cargo.toml') }}-
+  #           ${{ matrix.os }}-cargo-${{ github.job }}-
+  #           ${{ matrix.os }}-cargo-
 
-      # Generate Cargo.lock files for build, sccache cache keys.
-      # Allows dependencies updated on crates.io between runs to trigger storing an updated cache,
-      # which hashing Cargo.toml files alone does not.
-      - name: Cargo update
-        uses: actions-rs/cargo@v1
-        with:
-          command: update
+  #     # Generate Cargo.lock files for build, sccache cache keys.
+  #     # Allows dependencies updated on crates.io between runs to trigger storing an updated cache,
+  #     # which hashing Cargo.toml files alone does not.
+  #     - name: Cargo update
+  #       uses: actions-rs/cargo@v1
+  #       with:
+  #         command: update
 
-      - name: Cache wasm target
-        uses: actions/cache@v2.1.4
-        with:
-          path: bindings/wasm/target
-          # Add date to the cache to keep it up to date
-          key: ${{ matrix.os }}-wasm-target-${{ github.job }}-${{ hashFiles('**/Cargo.lock') }}
-          # Restore from outdated cache for speed
-          restore-keys: |
-            ${{ matrix.os }}-wasm-target-${{ github.job }}-
-            ${{ matrix.os }}-wasm-target-
+  #     - name: Cache wasm target
+  #       uses: actions/cache@v2.1.4
+  #       with:
+  #         path: bindings/wasm/target
+  #         # Add date to the cache to keep it up to date
+  #         key: ${{ matrix.os }}-wasm-target-${{ github.job }}-${{ hashFiles('**/Cargo.lock') }}
+  #         # Restore from outdated cache for speed
+  #         restore-keys: |
+  #           ${{ matrix.os }}-wasm-target-${{ github.job }}-
+  #           ${{ matrix.os }}-wasm-target-
 
-      - uses: './.github/actions/sccache/install-and-start-sccache-ubuntu'
-        name: install-and-start-sccache-ubuntu
-        if: matrix.os == 'ubuntu-latest'
-        with:
-          cache-path: ${{ matrix.sccache-path }}
-          cache-key: ${{ runner.os }}-sccache-${{ github.job }}-${{ hashFiles('**/Cargo.lock') }}
-          cache-restore-keys: |
-            ${{ runner.os }}-sccache-${{ github.job }}-
-            ${{ runner.os }}-sccache-
+  #     - uses: './.github/actions/rust/sccache/install-and-start-sccache-ubuntu'
+  #       name: install-and-start-sccache-ubuntu
+  #       if: matrix.os == 'ubuntu-latest'
 
-      - name: Set up Node.js
-        uses: actions/setup-node@v1
-        with:
-          node-version: 15.x
+  #     - name: Set up Node.js
+  #       uses: actions/setup-node@v1
+  #       with:
+  #         node-version: 15.x
 
-      - name: Install wasm-pack
-        run: npm install -g wasm-pack
+  #     - name: Install wasm-pack
+  #       run: npm install -g wasm-pack
 
-      - name: Install JS dependencies
-        run: npm install
-        working-directory: bindings/wasm
+  #     - name: Install JS dependencies
+  #       run: npm install
+  #       working-directory: bindings/wasm
 
-      - name: Build WASM bindings
-        run: npm run build
-        working-directory: bindings/wasm
+  #     - name: Build WASM bindings
+  #       run: npm run build
+  #       working-directory: bindings/wasm
 
-      - name: Build Wasm examples
-        run: npm run build:examples
-        working-directory: bindings/wasm
+  #     - name: Build Wasm examples
+  #       run: npm run build:examples
+  #       working-directory: bindings/wasm
 
-      - name: Run tests
-        uses: actions-rs/cargo@v1
-        with:
-          command: test
-          args: --manifest-path ./bindings/wasm/Cargo.toml --release
+  #     - name: Run tests
+  #       uses: actions-rs/cargo@v1
+  #       with:
+  #         command: test
+  #         args: --manifest-path ./bindings/wasm/Cargo.toml --release
 
-      - name: Run wasm-bindgen tests # tests annotated with #[wasm_bindgen_test]
-        run: wasm-pack test --node
-        working-directory: bindings/wasm
+  #     - name: Run wasm-bindgen tests # tests annotated with #[wasm_bindgen_test]
+  #       run: wasm-pack test --node
+  #       working-directory: bindings/wasm
 
-      - name: Stop sccache server
-        run: sccache --stop-server || true
+  #     - name: Stop sccache server
+  #       run: sccache --stop-server || true
